= Code Promotion across Environments

== Introduction

In this lab we will learn how an application image binary can be promoted across the environments. As an example we will use development and QA environments as promotion to pre-prod and production will be very similar.

In this example we are using projects as means of separation of environments (development, qa, production).

== Create and Setup Environments for Code Promotion

* Create two projects (Development and Testing)

Using the knowledge you gained from the past create two projects. Name the first project *development-%username%*

....
$ oc new-project development-%username%
....

Name the second *testing-%username%*.
....
$ oc new-project testing-%username%
....

*Remember* to substitute the username!

* Provide ImagePuller Access to the QA Project from Development Project

The following command will allow the QA project to be able to pull the container images from the Development project.

....
$ oc policy add-role-to-group system:image-puller system:serviceaccounts:testing-%username% -n development-%username%
....

== Deploy application


* Create an application in the development project

Switch over to the *development-%username%* project and deploy an application using the `php` s2i builder. You can use web console or
command line. The command line option is shown below.

*Bonus points:* Clone this application to your own github account and deploy it so that you can redeploy with changes later.

....
oc project development-%username%
oc new-app openshift/php~https://github.com/RedHatWorkshops/welcome-php
....

* Tag the Container Image

Wait until the application gets built and deployed. Now if you check the imagestreams you will find the container image for this application.

**Note** You can find the imagestream name using the following command. `is` is the
short form for `imageStream`.

....
$ oc get is                                                                            
NAME          IMAGE REPOSITORY                                                                 TAGS     UPDA
TED                                                                                                         
welcome-php   image-registry.openshift-image-registry.svc:5000/development-user1/welcome-php   latest   12 s
econds ago
....

Lets monitor the build progress 
----
$ oc logs bc/welcome-php -f
...
Pushing image image-registry.openshift-image-registry.svc:5000/development-user5/welcome-php:latest ...
Getting image source signatures
Copying blob sha256:ddffe1163fdc80f5136e19d0a5ed566fa4388722ec8c640501644fc0d9c69926
Copying blob sha256:f8a8d6ccf58e36e557a55b57a44daa973c61a637be5cab2fb38e3c9b737151df
Copying blob sha256:a03401a44180b6581a149376d6fd2d5bd85d938445fd5b5ad270e14ddde4937c
Copying blob sha256:dd3691704af8eb0ef955519328f2e6852ba398b0e316255913e2bfa0e6e57a4b
Copying blob sha256:5b76785eb746989e70f89e121d1223fe55a48b3e51ea5da51ed9e40e1ce0d15b
Copying blob sha256:bb0da44cdbced801240e74437a617d4fe0e39c29cf3bbabb7f6a96d2620cfeaa
Copying config sha256:790efe026da258d74c428b99b327b506593dd72b946668ec8a1196d67d61b7a8
Writing manifest to image destination
Storing signatures
Successfully pushed image-registry.openshift-image-registry.svc:5000/development-user5/welcome-php@sha256:9fa6414bbf96dc
04811cd96311a9de2d0a017935617233f610a593c54ff8275a
Push successful
---

Now describe this imagestream. It will show you full image id and the current tags assigned to that image. You'll notice that only `latest` is assigned right now.

....
$ oc get is                                                                            
NAME          IMAGE REPOSITORY                                                                 TAGS     UPDA
TED                                                                                                         
welcome-php   image-registry.openshift-image-registry.svc:5000/development-user1/welcome-php   latest   About a minute ago                                                                                              
---

Describe image stream 
---
[user2@cli-2-b2pms ~]$ oc describe is welcome-php                                                           
Name:                   welcome-php                                                                         
Namespace:              development-user1                                                                   
Created:                2 minutes ago                                                                       
Labels:                 app=welcome-php                                                                     
                        app.kubernetes.io/component=welcome-php                                             
                        app.kubernetes.io/instance=welcome-php                                              
Annotations:            openshift.io/generated-by=OpenShiftNewApp                                           
Image Repository:       image-registry.openshift-image-registry.svc:5000/development-user1/welcome-php      
Image Lookup:           local=false                                                                         
Unique Images:          1                                                                                   
Tags:                   1                                                                                   
                                                                                                            
latest                                                                                                      
  no spec tag                                                                                               
                                                                                                            
  * image-registry.openshift-image-registry.svc:5000/development-%username%/welcome-php@sha256:ba7dd4e757e2b20851
e7becc5fd2c2b38e1ee15165f2777fdc1c46ebd43c80a4
....

In general, when you are in development, you may be building your application multiple times,and test it. When a particular image passes your tests it will be promoted to QA.

Now let us assume that this container image is good and is ready to promote to QA. Let us tag this image using the `oc tag` command. We will pick up the latest image built and tested and add a tag to it as `promote-qa` as shown below:

*Remember* to substitute your %username%.

....
oc tag development-%username%/welcome-php:latest development-%username%/welcome-php:promote-qa

Tag welcome-php:promote-qa set to development-user1/welcome-php@sha256:ba7dd4e757e2b20851e7becc5fd2c2b38e1ee
15165f2777fdc1c46ebd43c80a4.
....

Check the following commands and replace the values of **%username%** where needed:

....
$ oc tag image-registry.openshift-image-registry.svc:5000/development-%username%/welcome-php
@sha256:99fd4920719fc8e7e9d4ff1c4e9a87b22ca802fdce006901a0cdd19fb9f2e14c development-%username%/welcome-php:promote-qa

Tag welcome-php:promote-qa set to image-registry.openshift-image-registry.svc:5000/development-%username%/welcome
-php@sha256:99fd4920719fc8e7e9d4ff1c4e9a87b22ca802fdce006901a0cdd19fb9f2e14c
....


Now describe the imagestream again to notice that a new tag `promote-qa` is applied now.

....
$ oc describe is welcome-php                                                           
Name:                   welcome-php                                                                         
Namespace:              development-user1                                                                   
Created:                19 minutes ago                                                                      
Labels:                 app=welcome-php                                                                     
                        app.kubernetes.io/component=welcome-php                                             
                        app.kubernetes.io/instance=welcome-php                                              
Annotations:            openshift.io/generated-by=OpenShiftNewApp                                           
Image Repository:       image-registry.openshift-image-registry.svc:5000/development-user1/welcome-php      
Image Lookup:           local=false                                                                         
Unique Images:          1                                                                                   
Tags:                   2                                                                                   
                                                                                                            
latest                                                                                                      
  no spec tag                                                                                               
                                                                                                            
  * image-registry.openshift-image-registry.svc:5000/development-user1/welcome-php@sha256:ba7dd4e757e2b20851
e7becc5fd2c2b38e1ee15165f2777fdc1c46ebd43c80a4                                                              
      18 minutes ago                                                                                        
                                                                                                            
promote-qa                                                                                                  
  tagged from welcome-php@sha256:ba7dd4e757e2b20851e7becc5fd2c2b38e1ee15165f2777fdc1c46ebd43c80a4           
                                                                                                            
  * image-registry.openshift-image-registry.svc:5000/development-user1/welcome-php@sha256:ba7dd4e757e2b20851
e7becc5fd2c2b38e1ee15165f2777fdc1c46ebd43c80a4                                                              
      About a minute ago                      
....

*Step 5: Deploy the application to QA*

Now you can switch over to the QA project and deploy the container image that we tagged as `promote-qa`. Note that the image is still in the development project. You are able to deploy that into testing project, because we gave necessary permissions for the testing project to be able to pull an image from development project.

Also expose service to create route for this project and *remember* to substitute username.

....
oc project testing-%username%
oc new-app development-%username%/welcome-php:promote-qa
oc expose service welcome-php
....

Test this application in the QA project. Note that we deployed the container image (`development-%username%/welcome-php:promote-qa`) from the development project without rebuilding the code.

*Bonus points*: Make changes to your git repo (to `index.php`) and deploy it to development first. Notice that your changes are seen only in development project. Repeat the changes a couple of times. Now find the `latest` imagestream and tag it as `promote-qa`. Watch out that the QA project gets redeployed when you
update the new tag.

Watch this
https://blog.openshift.com/promoting-applications-across-environments[video] for complete understanding.


== Summary

You now know how to promote your application across environments in OpenShift.
